---
pynet-rtr1:
    hostname: cisco1.domain.com
    groups: 
      - cisco-ios

pynet-rtr2:
    hostname: cisco2.domain.com
    groups: 
      - cisco-ios

arista1:
    hostname: arista1.domain.com
    groups: 
      - arista

arista2:
    hostname: arista2.domain.com
    groups: 
      - arista

arista3:
    hostname: arista3.domain.com
    groups: 
      - arista

arista4:
    hostname: arista4.domain.com
    groups: 
      - arista

arista5:
    hostname: arista5.domain.com
    groups: 
      - arista

arista6:
    hostname: arista6.domain.com
    groups: 
      - arista

arista7:
    hostname: arista7.domain.com
    groups: 
      - arista

arista8:
    hostname: arista8.domain.com
    groups: 
      - arista

nxos1:
    hostname: nxos1.domain.com
    groups: 
      - nxos

nxos2:
    hostname: nxos2.domain.com
    groups: 
      - nxos
